# ActivityPolicies for DNS Operator API group (dns.networking.miloapis.com)
# Resources: DNSZone, DNSRecordSet, DNSZoneClass, DNSZoneDiscovery

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: dns-zones
spec:
  resource:
    apiGroup: dns.networking.miloapis.com
    kind: DNSZone
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} added DNS zone {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed DNS zone {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch'] && audit.objectRef.subresource == 'status'"
      summary: "{{ link(audit.objectRef.name, audit.objectRef) }} DNS zone status changed"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated DNS zone {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified DNS zone {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: dns-recordsets
spec:
  resource:
    apiGroup: dns.networking.miloapis.com
    kind: DNSRecordSet
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} added DNS records {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed DNS records {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch'] && audit.objectRef.subresource == 'status'"
      summary: "{{ link(audit.objectRef.name, audit.objectRef) }} DNS record status changed"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated DNS records {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified DNS records {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: dns-zoneclasses
spec:
  resource:
    apiGroup: dns.networking.miloapis.com
    kind: DNSZoneClass
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created DNS zone class {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed DNS zone class {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated DNS zone class {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified DNS zone class {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: dns-zonediscoveries
spec:
  resource:
    apiGroup: dns.networking.miloapis.com
    kind: DNSZoneDiscovery
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} started DNS record discovery for {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed DNS discovery {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch'] && audit.objectRef.subresource == 'status'"
      summary: "{{ link(audit.objectRef.name, audit.objectRef) }} DNS discovery completed"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified DNS discovery {{ link(audit.objectRef.name, audit.objectRef) }}"
