// +k8s:openapi-gen=true
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	auditv1 "k8s.io/apiserver/pkg/apis/audit/v1"
)

// +genclient
// +genclient:nonNamespaced
// +genclient:onlyVerbs=create
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PolicyPreview tests an ActivityPolicy against sample inputs without persisting anything.
// Use this to verify that your policy rules match correctly and generate the expected summaries
// before deploying the policy.
//
// The preview accepts multiple inputs (audit logs and/or events) and returns the rendered
// Activity stream that would be generated by the policy.
//
// Example:
//
//	apiVersion: activity.miloapis.com/v1alpha1
//	kind: PolicyPreview
//	metadata:
//	  name: test-preview
//	spec:
//	  policy:
//	    resource:
//	      apiGroup: networking.datumapis.com
//	      kind: HTTPProxy
//	    auditRules:
//	      - match: "audit.verb == 'create'"
//	        summary: "{{ actor }} created {{ kind }}"
//	      - match: "audit.verb == 'delete'"
//	        summary: "{{ actor }} deleted {{ kind }}"
//	  inputs:
//	    - type: audit
//	      audit:
//	        verb: create
//	        objectRef:
//	          apiGroup: networking.datumapis.com
//	          resource: httpproxies
//	          name: my-proxy
//	        user:
//	          username: alice@example.com
//	    - type: audit
//	      audit:
//	        verb: delete
//	        objectRef:
//	          apiGroup: networking.datumapis.com
//	          resource: httpproxies
//	          name: old-proxy
//	        user:
//	          username: bob@example.com
type PolicyPreview struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PolicyPreviewSpec   `json:"spec"`
	Status PolicyPreviewStatus `json:"status,omitempty"`
}

// PolicyPreviewSpec defines the policy and inputs to test.
type PolicyPreviewSpec struct {
	// Policy is the ActivityPolicy spec to test.
	// You can use the full spec from an existing policy or create a new one.
	//
	// +required
	Policy ActivityPolicySpec `json:"policy"`

	// Inputs contains sample audit logs and/or events to test against the policy.
	// Each input is evaluated independently and produces an Activity if a rule matches.
	// You can mix audit logs and events in the same request.
	//
	// +required
	// +listType=atomic
	Inputs []PolicyPreviewInput `json:"inputs"`

	// KindLabel is the human-readable label for the resource kind.
	// If not specified, defaults to the Kind with spaces before capitals.
	//
	// +optional
	KindLabel string `json:"kindLabel,omitempty"`

	// KindLabelPlural is the plural form of the kind label.
	// If not specified, defaults to KindLabel + "s".
	//
	// +optional
	KindLabelPlural string `json:"kindLabelPlural,omitempty"`
}

// PolicyPreviewInput contains the sample input for policy testing.
type PolicyPreviewInput struct {
	// Type indicates whether this is an audit log or event input.
	// Values: "audit", "event"
	//
	// +required
	Type string `json:"type"`

	// Audit contains a sample audit log entry.
	// Required when Type is "audit".
	//
	// +optional
	Audit *auditv1.Event `json:"audit,omitempty"`

	// Event contains a sample Kubernetes event.
	// Required when Type is "event".
	// Uses RawExtension to allow flexible event structure.
	//
	// +optional
	Event *runtime.RawExtension `json:"event,omitempty"`
}

// PolicyPreviewStatus contains the preview results.
type PolicyPreviewStatus struct {
	// Activities contains the rendered Activity objects for inputs that matched a rule.
	// The order corresponds to the order of matched inputs (not necessarily the input order).
	// Inputs that don't match any rule are not included here.
	//
	// +optional
	// +listType=atomic
	Activities []Activity `json:"activities,omitempty"`

	// Results contains detailed results for each input, in the same order as spec.inputs.
	// Use this to see which inputs matched and any errors that occurred.
	//
	// +optional
	// +listType=atomic
	Results []PolicyPreviewInputResult `json:"results,omitempty"`

	// Error contains a general error message if the preview failed entirely.
	// Individual input errors are reported in results[].error.
	//
	// +optional
	Error string `json:"error,omitempty"`
}

// PolicyPreviewInputResult contains the result for a single input.
type PolicyPreviewInputResult struct {
	// InputIndex is the index of this input in spec.inputs (0-based).
	InputIndex int `json:"inputIndex"`

	// Matched indicates whether any rule matched this input.
	Matched bool `json:"matched"`

	// MatchedRuleIndex is the index of the rule that matched (0-based).
	// -1 if no rule matched.
	MatchedRuleIndex int `json:"matchedRuleIndex"`

	// MatchedRuleType indicates whether the matched rule was an audit or event rule.
	// Empty if no rule matched.
	MatchedRuleType string `json:"matchedRuleType,omitempty"`

	// Error contains any error message if evaluating this input failed.
	// This could be a CEL compilation error or evaluation error.
	//
	// +optional
	Error string `json:"error,omitempty"`
}
