// +k8s:openapi-gen=true
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	auditv1 "k8s.io/apiserver/pkg/apis/audit/v1"
)

// +genclient
// +genclient:nonNamespaced
// +genclient:onlyVerbs=create
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PolicyPreview tests an ActivityPolicy against sample inputs without persisting anything.
// Use this to verify that your policy rules match correctly and generate the expected summaries
// before deploying the policy.
//
// The preview accepts multiple inputs (audit logs and/or events) and returns the rendered
// Activity stream that would be generated by the policy.
//
// Example:
//
//	apiVersion: activity.miloapis.com/v1alpha1
//	kind: PolicyPreview
//	metadata:
//	  name: test-preview
//	spec:
//	  policy:
//	    resource:
//	      apiGroup: networking.datumapis.com
//	      kind: HTTPProxy
//	    auditRules:
//	      - match: "verb == 'create'"
//	        summary: "{{ actor }} created HTTPProxy"
//	      - match: "verb == 'delete'"
//	        summary: "{{ actor }} deleted HTTPProxy"
//	  inputs:
//	    - type: audit
//	      audit:
//	        verb: create
//	        objectRef:
//	          apiGroup: networking.datumapis.com
//	          resource: httpproxies
//	          name: my-proxy
//	        user:
//	          username: alice@example.com
//	    - type: audit
//	      audit:
//	        verb: delete
//	        objectRef:
//	          apiGroup: networking.datumapis.com
//	          resource: httpproxies
//	          name: old-proxy
//	        user:
//	          username: bob@example.com
type PolicyPreview struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PolicyPreviewSpec   `json:"spec"`
	Status PolicyPreviewStatus `json:"status,omitempty"`
}

// PolicyPreviewSpec defines the policy and inputs to test.
type PolicyPreviewSpec struct {
	// Policy is the ActivityPolicy spec to test.
	// You can use the full spec from an existing policy or create a new one.
	//
	// +required
	Policy ActivityPolicySpec `json:"policy"`

	// Inputs contains sample audit logs and/or events to test against the policy.
	// Each input is evaluated independently and produces an Activity if a rule matches.
	// You can mix audit logs and events in the same request.
	// Optional when AutoFetch is specified.
	//
	// +optional
	// +listType=atomic
	Inputs []PolicyPreviewInput `json:"inputs,omitempty"`

	// AutoFetch automatically retrieves sample inputs based on the policy resource type.
	// When specified, the API queries recent audit logs and/or events matching the policy.
	// Mutually exclusive with manual inputs - only one should be provided.
	//
	// +optional
	AutoFetch *AutoFetchSpec `json:"autoFetch,omitempty"`

	// KindLabel overrides the display label for the resource kind.
	//
	// +optional
	KindLabel string `json:"kindLabel,omitempty"`

	// KindLabelPlural overrides the plural display label.
	//
	// +optional
	KindLabelPlural string `json:"kindLabelPlural,omitempty"`
}

// PolicyPreviewInput contains the sample input for policy testing.
type PolicyPreviewInput struct {
	// Type indicates whether this is an audit log or event input.
	// Values: "audit", "event"
	//
	// +required
	Type string `json:"type"`

	// Audit contains a sample audit log entry.
	// Required when Type is "audit".
	//
	// +optional
	Audit *auditv1.Event `json:"audit,omitempty"`

	// Event contains a sample Kubernetes event.
	// Required when Type is "event".
	// Uses RawExtension to allow flexible event structure.
	//
	// +optional
	Event *runtime.RawExtension `json:"event,omitempty"`
}

// AutoFetchSpec configures automatic sample data retrieval.
type AutoFetchSpec struct {
	// Limit is the maximum number of sample inputs to fetch (default: 10, max: 50).
	// The API fetches up to this many audit logs and/or events.
	//
	// +optional
	// +kubebuilder:default=10
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=50
	Limit int32 `json:"limit,omitempty"`

	// TimeRange specifies how far back to look for samples (default: "24h").
	// Supports relative format: "1h", "24h", "7d", "30d"
	//
	// +optional
	// +kubebuilder:default="24h"
	TimeRange string `json:"timeRange,omitempty"`

	// Sources specifies which data sources to query: "audit", "events", or "both" (default: "both").
	// - "audit": Only fetch audit logs (only tests auditRules)
	// - "events": Only fetch Kubernetes events (only tests eventRules)
	// - "both": Fetch both types (tests all rules)
	//
	// +optional
	// +kubebuilder:default="both"
	// +kubebuilder:validation:Enum=audit;events;both
	Sources string `json:"sources,omitempty"`
}

// PolicyPreviewStatus contains the preview results.
type PolicyPreviewStatus struct {
	// Activities contains the rendered Activity objects for inputs that matched a rule.
	// The order corresponds to the order of matched inputs (not necessarily the input order).
	// Inputs that don't match any rule are not included here.
	//
	// +optional
	// +listType=atomic
	Activities []Activity `json:"activities,omitempty"`

	// Results contains detailed results for each input, in the same order as spec.inputs.
	// Use this to see which inputs matched and any errors that occurred.
	//
	// +optional
	// +listType=atomic
	Results []PolicyPreviewInputResult `json:"results,omitempty"`

	// FetchedInputs contains the auto-fetched sample inputs (only present when autoFetch was used).
	// This allows clients to see what data was tested.
	//
	// +optional
	// +listType=atomic
	FetchedInputs []PolicyPreviewInput `json:"fetchedInputs,omitempty"`

	// Error contains a general error message if the preview failed entirely.
	// Individual input errors are reported in results[].error.
	//
	// +optional
	Error string `json:"error,omitempty"`
}

// PolicyPreviewInputResult contains the result for a single input.
type PolicyPreviewInputResult struct {
	// InputIndex is the index of this input in spec.inputs (0-based).
	InputIndex int `json:"inputIndex"`

	// Matched indicates whether any rule matched this input.
	Matched bool `json:"matched"`

	// MatchedRuleIndex is the index of the rule that matched (0-based).
	// -1 if no rule matched.
	MatchedRuleIndex int `json:"matchedRuleIndex"`

	// MatchedRuleType indicates whether the matched rule was an audit or event rule.
	// Empty if no rule matched.
	MatchedRuleType string `json:"matchedRuleType,omitempty"`

	// MatchedRuleName is the name of the rule that matched this input.
	// This is the value from the rule's Name field in the policy spec.
	// Empty if no rule matched.
	//
	// +optional
	MatchedRuleName string `json:"matchedRuleName,omitempty"`

	// Error contains any error message if evaluating this input failed.
	// This could be a CEL compilation error or evaluation error.
	//
	// +optional
	Error string `json:"error,omitempty"`
}
