//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	eventsv1 "k8s.io/api/events/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	auditv1 "k8s.io/apiserver/pkg/apis/audit/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activity) DeepCopyInto(out *Activity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activity.
func (in *Activity) DeepCopy() *Activity {
	if in == nil {
		return nil
	}
	out := new(Activity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Activity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityActor) DeepCopyInto(out *ActivityActor) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityActor.
func (in *ActivityActor) DeepCopy() *ActivityActor {
	if in == nil {
		return nil
	}
	out := new(ActivityActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityChange) DeepCopyInto(out *ActivityChange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityChange.
func (in *ActivityChange) DeepCopy() *ActivityChange {
	if in == nil {
		return nil
	}
	out := new(ActivityChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityFacetQuery) DeepCopyInto(out *ActivityFacetQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityFacetQuery.
func (in *ActivityFacetQuery) DeepCopy() *ActivityFacetQuery {
	if in == nil {
		return nil
	}
	out := new(ActivityFacetQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityFacetQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityFacetQuerySpec) DeepCopyInto(out *ActivityFacetQuerySpec) {
	*out = *in
	out.TimeRange = in.TimeRange
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityFacetQuerySpec.
func (in *ActivityFacetQuerySpec) DeepCopy() *ActivityFacetQuerySpec {
	if in == nil {
		return nil
	}
	out := new(ActivityFacetQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityFacetQueryStatus) DeepCopyInto(out *ActivityFacetQueryStatus) {
	*out = *in
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityFacetQueryStatus.
func (in *ActivityFacetQueryStatus) DeepCopy() *ActivityFacetQueryStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityFacetQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityLink) DeepCopyInto(out *ActivityLink) {
	*out = *in
	out.Resource = in.Resource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityLink.
func (in *ActivityLink) DeepCopy() *ActivityLink {
	if in == nil {
		return nil
	}
	out := new(ActivityLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityList) DeepCopyInto(out *ActivityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Activity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityList.
func (in *ActivityList) DeepCopy() *ActivityList {
	if in == nil {
		return nil
	}
	out := new(ActivityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityOrigin) DeepCopyInto(out *ActivityOrigin) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityOrigin.
func (in *ActivityOrigin) DeepCopy() *ActivityOrigin {
	if in == nil {
		return nil
	}
	out := new(ActivityOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicy) DeepCopyInto(out *ActivityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicy.
func (in *ActivityPolicy) DeepCopy() *ActivityPolicy {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyList) DeepCopyInto(out *ActivityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActivityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyList.
func (in *ActivityPolicyList) DeepCopy() *ActivityPolicyList {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyResource) DeepCopyInto(out *ActivityPolicyResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyResource.
func (in *ActivityPolicyResource) DeepCopy() *ActivityPolicyResource {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyRule) DeepCopyInto(out *ActivityPolicyRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyRule.
func (in *ActivityPolicyRule) DeepCopy() *ActivityPolicyRule {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicySpec) DeepCopyInto(out *ActivityPolicySpec) {
	*out = *in
	out.Resource = in.Resource
	if in.AuditRules != nil {
		in, out := &in.AuditRules, &out.AuditRules
		*out = make([]ActivityPolicyRule, len(*in))
		copy(*out, *in)
	}
	if in.EventRules != nil {
		in, out := &in.EventRules, &out.EventRules
		*out = make([]ActivityPolicyRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicySpec.
func (in *ActivityPolicySpec) DeepCopy() *ActivityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyStatus) DeepCopyInto(out *ActivityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyStatus.
func (in *ActivityPolicyStatus) DeepCopy() *ActivityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityQuery) DeepCopyInto(out *ActivityQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityQuery.
func (in *ActivityQuery) DeepCopy() *ActivityQuery {
	if in == nil {
		return nil
	}
	out := new(ActivityQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityQuerySpec) DeepCopyInto(out *ActivityQuerySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityQuerySpec.
func (in *ActivityQuerySpec) DeepCopy() *ActivityQuerySpec {
	if in == nil {
		return nil
	}
	out := new(ActivityQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityQueryStatus) DeepCopyInto(out *ActivityQueryStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]Activity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityQueryStatus.
func (in *ActivityQueryStatus) DeepCopy() *ActivityQueryStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityResource) DeepCopyInto(out *ActivityResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityResource.
func (in *ActivityResource) DeepCopy() *ActivityResource {
	if in == nil {
		return nil
	}
	out := new(ActivityResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivitySpec) DeepCopyInto(out *ActivitySpec) {
	*out = *in
	out.Actor = in.Actor
	out.Resource = in.Resource
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]ActivityLink, len(*in))
		copy(*out, *in)
	}
	out.Tenant = in.Tenant
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]ActivityChange, len(*in))
		copy(*out, *in)
	}
	out.Origin = in.Origin
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivitySpec.
func (in *ActivitySpec) DeepCopy() *ActivitySpec {
	if in == nil {
		return nil
	}
	out := new(ActivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityTenant) DeepCopyInto(out *ActivityTenant) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityTenant.
func (in *ActivityTenant) DeepCopy() *ActivityTenant {
	if in == nil {
		return nil
	}
	out := new(ActivityTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQuery) DeepCopyInto(out *AuditLogFacetsQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQuery.
func (in *AuditLogFacetsQuery) DeepCopy() *AuditLogFacetsQuery {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogFacetsQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQuerySpec) DeepCopyInto(out *AuditLogFacetsQuerySpec) {
	*out = *in
	out.TimeRange = in.TimeRange
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQuerySpec.
func (in *AuditLogFacetsQuerySpec) DeepCopy() *AuditLogFacetsQuerySpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQueryStatus) DeepCopyInto(out *AuditLogFacetsQueryStatus) {
	*out = *in
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQueryStatus.
func (in *AuditLogFacetsQueryStatus) DeepCopy() *AuditLogFacetsQueryStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQuery) DeepCopyInto(out *AuditLogQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQuery.
func (in *AuditLogQuery) DeepCopy() *AuditLogQuery {
	if in == nil {
		return nil
	}
	out := new(AuditLogQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQuerySpec) DeepCopyInto(out *AuditLogQuerySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQuerySpec.
func (in *AuditLogQuerySpec) DeepCopy() *AuditLogQuerySpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQueryStatus) DeepCopyInto(out *AuditLogQueryStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]auditv1.Event, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQueryStatus.
func (in *AuditLogQueryStatus) DeepCopy() *AuditLogQueryStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLogQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFacetQuery) DeepCopyInto(out *EventFacetQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFacetQuery.
func (in *EventFacetQuery) DeepCopy() *EventFacetQuery {
	if in == nil {
		return nil
	}
	out := new(EventFacetQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventFacetQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFacetQuerySpec) DeepCopyInto(out *EventFacetQuerySpec) {
	*out = *in
	out.TimeRange = in.TimeRange
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFacetQuerySpec.
func (in *EventFacetQuerySpec) DeepCopy() *EventFacetQuerySpec {
	if in == nil {
		return nil
	}
	out := new(EventFacetQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventFacetQueryStatus) DeepCopyInto(out *EventFacetQueryStatus) {
	*out = *in
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventFacetQueryStatus.
func (in *EventFacetQueryStatus) DeepCopy() *EventFacetQueryStatus {
	if in == nil {
		return nil
	}
	out := new(EventFacetQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventQuery) DeepCopyInto(out *EventQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventQuery.
func (in *EventQuery) DeepCopy() *EventQuery {
	if in == nil {
		return nil
	}
	out := new(EventQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventQueryList) DeepCopyInto(out *EventQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EventQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventQueryList.
func (in *EventQueryList) DeepCopy() *EventQueryList {
	if in == nil {
		return nil
	}
	out := new(EventQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventQuerySpec) DeepCopyInto(out *EventQuerySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventQuerySpec.
func (in *EventQuerySpec) DeepCopy() *EventQuerySpec {
	if in == nil {
		return nil
	}
	out := new(EventQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventQueryStatus) DeepCopyInto(out *EventQueryStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]eventsv1.Event, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventQueryStatus.
func (in *EventQueryStatus) DeepCopy() *EventQueryStatus {
	if in == nil {
		return nil
	}
	out := new(EventQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResult) DeepCopyInto(out *FacetResult) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]FacetValue, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResult.
func (in *FacetResult) DeepCopy() *FacetResult {
	if in == nil {
		return nil
	}
	out := new(FacetResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSpec) DeepCopyInto(out *FacetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSpec.
func (in *FacetSpec) DeepCopy() *FacetSpec {
	if in == nil {
		return nil
	}
	out := new(FacetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetTimeRange) DeepCopyInto(out *FacetTimeRange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetTimeRange.
func (in *FacetTimeRange) DeepCopy() *FacetTimeRange {
	if in == nil {
		return nil
	}
	out := new(FacetTimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetValue) DeepCopyInto(out *FacetValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetValue.
func (in *FacetValue) DeepCopy() *FacetValue {
	if in == nil {
		return nil
	}
	out := new(FacetValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPreview) DeepCopyInto(out *PolicyPreview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPreview.
func (in *PolicyPreview) DeepCopy() *PolicyPreview {
	if in == nil {
		return nil
	}
	out := new(PolicyPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyPreview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPreviewInput) DeepCopyInto(out *PolicyPreviewInput) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(auditv1.Event)
		(*in).DeepCopyInto(*out)
	}
	if in.Event != nil {
		in, out := &in.Event, &out.Event
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPreviewInput.
func (in *PolicyPreviewInput) DeepCopy() *PolicyPreviewInput {
	if in == nil {
		return nil
	}
	out := new(PolicyPreviewInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPreviewInputResult) DeepCopyInto(out *PolicyPreviewInputResult) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPreviewInputResult.
func (in *PolicyPreviewInputResult) DeepCopy() *PolicyPreviewInputResult {
	if in == nil {
		return nil
	}
	out := new(PolicyPreviewInputResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPreviewSpec) DeepCopyInto(out *PolicyPreviewSpec) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]PolicyPreviewInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPreviewSpec.
func (in *PolicyPreviewSpec) DeepCopy() *PolicyPreviewSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyPreviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPreviewStatus) DeepCopyInto(out *PolicyPreviewStatus) {
	*out = *in
	if in.Activities != nil {
		in, out := &in.Activities, &out.Activities
		*out = make([]Activity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]PolicyPreviewInputResult, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPreviewStatus.
func (in *PolicyPreviewStatus) DeepCopy() *PolicyPreviewStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyPreviewStatus)
	in.DeepCopyInto(out)
	return out
}
