//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated manually. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Activity) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.Activity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ActivityList) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.ActivityList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ActivityFacetQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.ActivityFacetQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ActivityPolicy) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.ActivityPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ActivityPolicyList) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.ActivityPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ActivityQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.ActivityQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.AuditLogQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogFacetsQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.AuditLogFacetsQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EventQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.EventQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EventQueryList) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.EventQueryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EventFacetQuery) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.EventFacetQuery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EventRecord) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.EventRecord"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PolicyPreview) OpenAPIModelName() string {
	return "go.miloapis.com/activity/pkg/apis/activity/v1alpha1.PolicyPreview"
}
