//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apiserver/pkg/apis/audit/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQuery) DeepCopyInto(out *AuditLogFacetsQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQuery.
func (in *AuditLogFacetsQuery) DeepCopy() *AuditLogFacetsQuery {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogFacetsQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQuerySpec) DeepCopyInto(out *AuditLogFacetsQuerySpec) {
	*out = *in
	out.TimeRange = in.TimeRange
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQuerySpec.
func (in *AuditLogFacetsQuerySpec) DeepCopy() *AuditLogFacetsQuerySpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogFacetsQueryStatus) DeepCopyInto(out *AuditLogFacetsQueryStatus) {
	*out = *in
	if in.Facets != nil {
		in, out := &in.Facets, &out.Facets
		*out = make([]FacetResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogFacetsQueryStatus.
func (in *AuditLogFacetsQueryStatus) DeepCopy() *AuditLogFacetsQueryStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLogFacetsQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQuery) DeepCopyInto(out *AuditLogQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQuery.
func (in *AuditLogQuery) DeepCopy() *AuditLogQuery {
	if in == nil {
		return nil
	}
	out := new(AuditLogQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQueryList) DeepCopyInto(out *AuditLogQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditLogQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQueryList.
func (in *AuditLogQueryList) DeepCopy() *AuditLogQueryList {
	if in == nil {
		return nil
	}
	out := new(AuditLogQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQuerySpec) DeepCopyInto(out *AuditLogQuerySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQuerySpec.
func (in *AuditLogQuerySpec) DeepCopy() *AuditLogQuerySpec {
	if in == nil {
		return nil
	}
	out := new(AuditLogQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogQueryStatus) DeepCopyInto(out *AuditLogQueryStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]v1.Event, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogQueryStatus.
func (in *AuditLogQueryStatus) DeepCopy() *AuditLogQueryStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLogQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResult) DeepCopyInto(out *FacetResult) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]FacetValue, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResult.
func (in *FacetResult) DeepCopy() *FacetResult {
	if in == nil {
		return nil
	}
	out := new(FacetResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSpec) DeepCopyInto(out *FacetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSpec.
func (in *FacetSpec) DeepCopy() *FacetSpec {
	if in == nil {
		return nil
	}
	out := new(FacetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetTimeRange) DeepCopyInto(out *FacetTimeRange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetTimeRange.
func (in *FacetTimeRange) DeepCopy() *FacetTimeRange {
	if in == nil {
		return nil
	}
	out := new(FacetTimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetValue) DeepCopyInto(out *FacetValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetValue.
func (in *FacetValue) DeepCopy() *FacetValue {
	if in == nil {
		return nil
	}
	out := new(FacetValue)
	in.DeepCopyInto(out)
	return out
}
