-- Migration: 002_activities_table
-- Description: Activities table for storing translated activity records
-- Author: Activity System
-- Date: 2026-02-02

-- ============================================================================
-- Activities Table
-- ============================================================================
-- Stores translated activity records generated by the Activity Processor.
-- These are human-readable summaries of audit logs and Kubernetes events,
-- optimized for time-range queries and multi-tenant isolation.

CREATE TABLE IF NOT EXISTS audit.activities
(
    -- Full activity record as JSON (compressed)
    activity_json String CODEC(ZSTD(3)),

    -- Core timestamp for time-range queries
    timestamp DateTime64(3) MATERIALIZED
        coalesce(
            parseDateTime64BestEffortOrNull(JSONExtractString(activity_json, 'metadata', 'creationTimestamp')),
            now64(3)
        ),

    -- Multi-tenant isolation
    tenant_type LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'tenant', 'type'), ''),

    tenant_name String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'tenant', 'name'), ''),

    -- Origin tracking for correlation to source records
    origin_type LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'origin', 'type'), ''),

    origin_id String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'origin', 'id'), ''),

    -- Change source classification (human vs system)
    change_source LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'changeSource'), ''),

    -- Actor information
    actor_type LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'actor', 'type'), ''),

    actor_name String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'actor', 'name'), ''),

    actor_uid String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'actor', 'uid'), ''),

    -- Resource information
    api_group LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'resource', 'apiGroup'), ''),

    resource_kind LowCardinality(String) MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'resource', 'kind'), ''),

    resource_name String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'resource', 'name'), ''),

    resource_namespace String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'resource', 'namespace'), ''),

    resource_uid String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'resource', 'uid'), ''),

    -- Activity metadata
    activity_name String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'metadata', 'name'), ''),

    activity_namespace String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'metadata', 'namespace'), ''),

    -- Summary for full-text search
    summary String MATERIALIZED
        coalesce(JSONExtractString(activity_json, 'spec', 'summary'), ''),

    -- ========================================================================
    -- Skip Indexes
    -- ========================================================================

    -- Bloom filter for API group filtering (service provider queries)
    INDEX idx_api_group api_group TYPE bloom_filter(0.01) GRANULARITY 1,

    -- Bloom filter for actor-based filtering
    INDEX idx_actor_name actor_name TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX idx_actor_uid actor_uid TYPE bloom_filter(0.001) GRANULARITY 1,

    -- Bloom filter for resource lookups
    INDEX idx_resource resource_kind TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_resource_name resource_name TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_resource_uid resource_uid TYPE bloom_filter(0.001) GRANULARITY 1,

    -- Minmax for change source filtering (human vs system)
    INDEX idx_change_source change_source TYPE set(10) GRANULARITY 4,

    -- Full-text index for summary search (ngrams enable substring/prefix matching)
    INDEX idx_summary_search summary TYPE text(tokenizer = ngrams(3)) GRANULARITY 1,

    -- ========================================================================
    -- Projections (defined inline for ReplicatedReplacingMergeTree compatibility)
    -- ========================================================================

    -- Projection for service provider queries (by API group)
    PROJECTION api_group_query_projection
    (
        SELECT *
        ORDER BY (api_group, timestamp, tenant_type, tenant_name, resource_uid)
    ),

    -- Projection for actor-based queries
    PROJECTION actor_query_projection
    (
        SELECT *
        ORDER BY (actor_name, timestamp, tenant_type, tenant_name, resource_uid)
    ),

    -- Projection for resource-specific queries
    PROJECTION resource_query_projection
    (
        SELECT *
        ORDER BY (resource_uid, timestamp)
    )
)
ENGINE = ReplicatedReplacingMergeTree
PARTITION BY toYYYYMMDD(timestamp)
-- Primary key optimized for tenant-scoped time-range queries
ORDER BY (tenant_type, tenant_name, timestamp, resource_uid)
PRIMARY KEY (tenant_type, tenant_name, timestamp, resource_uid)

-- 30-day retention for activities
TTL timestamp + INTERVAL 30 DAY DELETE

SETTINGS
    storage_policy = 'default',
    ttl_only_drop_parts = 1,
    deduplicate_merge_projection_mode = 'rebuild';
