#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
MODULE_NAME="go.miloapis.com/activity"
OPENAPI_FILE="${SCRIPT_ROOT}/pkg/generated/openapi/zz_generated.openapi.go"
OUTPUT_FILE="${SCRIPT_ROOT}/pkg/apis/activity/v1alpha1/zz_generated.model_name.go"

if [ ! -f "${OPENAPI_FILE}" ]; then
    echo "ERROR: OpenAPI definitions not found at ${OPENAPI_FILE}"
    echo "Run: task generate:openapi"
    exit 1
fi

echo "Extracting type names from OpenAPI definitions..."

# Extract all v1alpha1 type references from the OpenAPI file
# These are the types that appear in the GetOpenAPIDefinitions function as v1alpha1.TypeName{}
TYPE_NAMES=$(grep -o 'v1alpha1\.[A-Za-z]*{}' "${OPENAPI_FILE}" | \
    sed 's/v1alpha1\.\([A-Za-z]*\){}/\1/' | \
    sort -u)

if [ -z "${TYPE_NAMES}" ]; then
    echo "ERROR: No v1alpha1 types found in OpenAPI definitions at ${OPENAPI_FILE}"
    echo "Make sure OpenAPI generation ran successfully first."
    exit 1
fi

echo "Found $(echo "${TYPE_NAMES}" | wc -l | tr -d ' ') types"

# Generate the Go file
cat > "${OUTPUT_FILE}" <<'EOF'
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hack/generate-model-names.sh. DO NOT EDIT.

package v1alpha1

EOF

# Generate OpenAPIModelName() method for each type
while IFS= read -r TYPE_NAME; do
    cat >> "${OUTPUT_FILE}" <<EOF
// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ${TYPE_NAME}) OpenAPIModelName() string {
	return "${MODULE_NAME}/pkg/apis/activity/v1alpha1.${TYPE_NAME}"
}

EOF
done <<< "${TYPE_NAMES}"

echo "Generated ${OUTPUT_FILE}"
echo ""
echo "Generated OpenAPIModelName() methods for:"
echo "${TYPE_NAMES}" | sed 's/^/  - /'
