// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ActivityLister helps list Activities.
// All objects returned here must be treated as read-only.
type ActivityLister interface {
	// List lists all Activities in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*activityv1alpha1.Activity, err error)
	// Activities returns an object that can list and get Activities.
	Activities(namespace string) ActivityNamespaceLister
	ActivityListerExpansion
}

// activityLister implements the ActivityLister interface.
type activityLister struct {
	listers.ResourceIndexer[*activityv1alpha1.Activity]
}

// NewActivityLister returns a new ActivityLister.
func NewActivityLister(indexer cache.Indexer) ActivityLister {
	return &activityLister{listers.New[*activityv1alpha1.Activity](indexer, activityv1alpha1.Resource("activity"))}
}

// Activities returns an object that can list and get Activities.
func (s *activityLister) Activities(namespace string) ActivityNamespaceLister {
	return activityNamespaceLister{listers.NewNamespaced[*activityv1alpha1.Activity](s.ResourceIndexer, namespace)}
}

// ActivityNamespaceLister helps list and get Activities.
// All objects returned here must be treated as read-only.
type ActivityNamespaceLister interface {
	// List lists all Activities in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*activityv1alpha1.Activity, err error)
	// Get retrieves the Activity from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*activityv1alpha1.Activity, error)
	ActivityNamespaceListerExpansion
}

// activityNamespaceLister implements the ActivityNamespaceLister
// interface.
type activityNamespaceLister struct {
	listers.ResourceIndexer[*activityv1alpha1.Activity]
}
