// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ActivityPolicyLister helps list ActivityPolicies.
// All objects returned here must be treated as read-only.
type ActivityPolicyLister interface {
	// List lists all ActivityPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*activityv1alpha1.ActivityPolicy, err error)
	// Get retrieves the ActivityPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*activityv1alpha1.ActivityPolicy, error)
	ActivityPolicyListerExpansion
}

// activityPolicyLister implements the ActivityPolicyLister interface.
type activityPolicyLister struct {
	listers.ResourceIndexer[*activityv1alpha1.ActivityPolicy]
}

// NewActivityPolicyLister returns a new ActivityPolicyLister.
func NewActivityPolicyLister(indexer cache.Indexer) ActivityPolicyLister {
	return &activityPolicyLister{listers.New[*activityv1alpha1.ActivityPolicy](indexer, activityv1alpha1.Resource("activitypolicy"))}
}
