// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActivityListerExpansion allows custom methods to be added to
// ActivityLister.
type ActivityListerExpansion interface{}

// ActivityNamespaceListerExpansion allows custom methods to be added to
// ActivityNamespaceLister.
type ActivityNamespaceListerExpansion interface{}

// ActivityPolicyListerExpansion allows custom methods to be added to
// ActivityPolicyLister.
type ActivityPolicyListerExpansion interface{}

// ReindexJobListerExpansion allows custom methods to be added to
// ReindexJobLister.
type ReindexJobListerExpansion interface{}
