// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActivityPolicyListerExpansion allows custom methods to be added to
// ActivityPolicyLister.
type ActivityPolicyListerExpansion interface{}
