import { useState } from 'react';
import type { ActivityApiClient } from '../api/client';
import type { ActivityPolicyResource } from '../types/policy';
import type { ResourceRef, ErrorFormatter } from '../types/activity';
import { EventsFeed } from './EventsFeed';
import { ActivityFeed } from './ActivityFeed';

export interface PolicyActivityViewProps {
  /** API client instance */
  client: ActivityApiClient;
  /** Policy resource configuration to filter by */
  policyResource: ActivityPolicyResource;
  /** Handler for resource link clicks in activity summaries */
  onResourceClick?: (resource: ResourceRef) => void;
  /** Additional CSS class */
  className?: string;
  /** Custom error formatter */
  errorFormatter?: ErrorFormatter;
}

type ViewMode = 'activity' | 'timeline';

/**
 * PolicyActivityView displays activity and timeline views for a specific policy.
 *
 * - Activity: Shows raw audit logs/events for this resource type (inputs to the policy)
 * - Timeline: Shows translated activities generated by this policy (outputs from the policy)
 */
export function PolicyActivityView({
  client,
  policyResource,
  onResourceClick,
  className = '',
  errorFormatter,
}: PolicyActivityViewProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('activity');

  // Build filters based on the policy's resource configuration
  const resourceKinds = policyResource.kind ? [policyResource.kind] : undefined;
  const involvedKinds = policyResource.kind ? [policyResource.kind] : undefined;

  return (
    <div className={className}>
      {/* Simple menu header */}
      <div className="flex items-center gap-4 mb-4 text-sm">
        <button
          onClick={() => setViewMode('activity')}
          className={`px-0 py-1 transition-colors ${
            viewMode === 'activity'
              ? 'text-foreground border-b-2 border-[#BF9595] font-medium'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          Activity
        </button>
        <span className="text-muted-foreground/30">|</span>
        <button
          onClick={() => setViewMode('timeline')}
          className={`px-0 py-1 transition-colors ${
            viewMode === 'timeline'
              ? 'text-foreground border-b-2 border-[#BF9595] font-medium'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          Timeline
        </button>
      </div>

      {/* Activity view - raw audit logs and events */}
      {viewMode === 'activity' && (
        <div className="space-y-4">
          <EventsFeed
            client={client}
            initialFilters={{
              involvedKinds,
            }}
            initialTimeRange={{ start: 'now-24h' }}
            pageSize={20}
            compact={true}
            showFilters={true}
            hiddenFilters={['involvedKinds']}
            enableStreaming={false}
            errorFormatter={errorFormatter}
          />
        </div>
      )}

      {/* Timeline view - activities generated by this policy */}
      {viewMode === 'timeline' && (
        <div className="space-y-4">
          {/*
            TODO: Once activities track which policy generated them (via metadata labels or spec field),
            filter by policy name instead of just resource kind.
            For now, showing all activities for this resource type.
          */}
          <ActivityFeed
            client={client}
            initialFilters={{
              resourceKinds,
              changeSource: 'human',
            }}
            initialTimeRange={{ start: 'now-7d' }}
            onResourceClick={onResourceClick}
            pageSize={20}
            compact={true}
            showFilters={true}
            hiddenFilters={['resourceKinds']}
            enableStreaming={false}
            errorFormatter={errorFormatter}
          />
        </div>
      )}
    </div>
  );
}
