import { useState } from 'react';
import type { ActivityApiClient } from '../api/client';
import type { ActivityPolicyResource } from '../types/policy';
import type { ResourceRef, ErrorFormatter } from '../types/activity';
import { EventsFeed } from './EventsFeed';
import { ActivityFeed } from './ActivityFeed';

export interface PolicyActivityViewProps {
  /** API client instance */
  client: ActivityApiClient;
  /** Policy resource configuration to filter by */
  policyResource: ActivityPolicyResource;
  /** Policy name for filtering events by the ActivityPolicy itself */
  policyName: string;
  /** Handler for resource link clicks in activity summaries */
  onResourceClick?: (resource: ResourceRef) => void;
  /** Additional CSS class */
  className?: string;
  /** Custom error formatter */
  errorFormatter?: ErrorFormatter;
}

type ViewMode = 'activity' | 'events';

/**
 * PolicyActivityView displays activity and timeline views for a specific policy.
 *
 * - Activity: Shows translated activities generated by this policy (outputs from the policy)
 * - Policy Events: Shows events related to the ActivityPolicy resource itself
 */
export function PolicyActivityView({
  client,
  policyResource,
  policyName,
  onResourceClick,
  className = '',
  errorFormatter,
}: PolicyActivityViewProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('events');

  // Build filters based on the policy's resource configuration
  const resourceKinds = policyResource.kind ? [policyResource.kind] : undefined;

  return (
    <div className={className}>
      {/* Simple menu header */}
      <div className="flex items-center gap-4 mb-4 text-sm">
        <button
          onClick={() => setViewMode('events')}
          className={`px-0 py-1 transition-colors ${
            viewMode === 'events'
              ? 'text-foreground border-b-2 border-[#BF9595] font-medium'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          Policy Events
        </button>
        <span className="text-muted-foreground/30">|</span>
        <button
          onClick={() => setViewMode('activity')}
          className={`px-0 py-1 transition-colors ${
            viewMode === 'activity'
              ? 'text-foreground border-b-2 border-[#BF9595] font-medium'
              : 'text-muted-foreground hover:text-foreground'
          }`}
        >
          Activity
        </button>
      </div>

      {/* Activity view - activities generated by this policy */}
      {viewMode === 'activity' && (
        <div className="space-y-4">
          {/*
            TODO: Once activities track which policy generated them (via metadata labels or spec field),
            filter by policy name instead of just resource kind.
            For now, showing all activities for this resource type.
          */}
          <ActivityFeed
            client={client}
            initialFilters={{
              resourceKinds,
              changeSource: 'human',
            }}
            initialTimeRange={{ start: 'now-7d' }}
            onResourceClick={onResourceClick}
            pageSize={20}
            compact={true}
            showFilters={true}
            hiddenFilters={['resourceKinds']}
            enableStreaming={false}
            errorFormatter={errorFormatter}
          />
        </div>
      )}

      {/* Policy Events view - events related to the ActivityPolicy resource itself */}
      {viewMode === 'events' && (
        <div className="space-y-4">
          <EventsFeed
            client={client}
            initialFilters={{
              involvedKinds: ['ActivityPolicy'],
              involvedName: policyName,
            }}
            initialTimeRange={{ start: 'now-24h' }}
            pageSize={20}
            compact={true}
            showFilters={true}
            hiddenFilters={['involvedKinds', 'involvedName']}
            enableStreaming={false}
            errorFormatter={errorFormatter}
          />
        </div>
      )}
    </div>
  );
}
