//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package activity

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicy) DeepCopyInto(out *ActivityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicy.
func (in *ActivityPolicy) DeepCopy() *ActivityPolicy {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyList) DeepCopyInto(out *ActivityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActivityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyList.
func (in *ActivityPolicyList) DeepCopy() *ActivityPolicyList {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyResource) DeepCopyInto(out *ActivityPolicyResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyResource.
func (in *ActivityPolicyResource) DeepCopy() *ActivityPolicyResource {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyRule) DeepCopyInto(out *ActivityPolicyRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyRule.
func (in *ActivityPolicyRule) DeepCopy() *ActivityPolicyRule {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicySpec) DeepCopyInto(out *ActivityPolicySpec) {
	*out = *in
	out.Resource = in.Resource
	if in.AuditRules != nil {
		in, out := &in.AuditRules, &out.AuditRules
		*out = make([]ActivityPolicyRule, len(*in))
		copy(*out, *in)
	}
	if in.EventRules != nil {
		in, out := &in.EventRules, &out.EventRules
		*out = make([]ActivityPolicyRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicySpec.
func (in *ActivityPolicySpec) DeepCopy() *ActivityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityPolicyStatus) DeepCopyInto(out *ActivityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityPolicyStatus.
func (in *ActivityPolicyStatus) DeepCopy() *ActivityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ActivityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
