# ActivityPolicies for apps Kubernetes API group
# Resources: Deployment, ReplicaSet, StatefulSet, DaemonSet
#
# These policies only generate activities for write operations (create, update, patch, delete).
# Read operations (get, list, watch) are excluded as they don't represent meaningful state changes.

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: apps-deployments
spec:
  resource:
    apiGroup: apps
    kind: Deployment
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} deployed {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"
    - match: "audit.verb in ['update', 'patch'] && has(audit.objectRef.subresource) && audit.objectRef.subresource == 'scale'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} scaled {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: apps-replicasets
spec:
  resource:
    apiGroup: apps
    kind: ReplicaSet
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created replicas for {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed replicas for {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"
    - match: "audit.verb in ['update', 'patch'] && has(audit.objectRef.subresource) && audit.objectRef.subresource == 'scale'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} scaled {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'replicas' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated replicas for {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'application' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: apps-statefulsets
spec:
  resource:
    apiGroup: apps
    kind: StatefulSet
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} deployed stateful app {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed stateful app {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch'] && has(audit.objectRef.subresource) && audit.objectRef.subresource == 'scale'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} scaled {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'stateful app' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated stateful app {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: apps-daemonsets
spec:
  resource:
    apiGroup: apps
    kind: DaemonSet
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} deployed cluster-wide service {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed cluster-wide service {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated cluster-wide service {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
