# ActivityPolicies for batch Kubernetes API group
# Resources: Job, CronJob
#
# These policies only generate activities for write operations (create, update, patch, delete).
# Read operations (get, list, watch) are excluded as they don't represent meaningful state changes.

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: batch-jobs
spec:
  resource:
    apiGroup: batch
    kind: Job
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} started job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} deleted job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: batch-cronjobs
spec:
  resource:
    apiGroup: batch
    kind: CronJob
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created scheduled job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} deleted scheduled job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated scheduled job {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
