# ActivityPolicies for core Kubernetes API group
# Resources: Pod, Service, ConfigMap, Secret, Namespace, ServiceAccount, PersistentVolumeClaim, PersistentVolume
#
# These policies only generate activities for write operations (create, update, patch, delete).
# Read operations (get, list, watch) are excluded as they don't represent meaningful state changes.

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-pods
spec:
  resource:
    apiGroup: ""
    kind: Pod
  auditRules:
    - match: "audit.verb == 'create' && has(audit.objectRef.subresource) && audit.objectRef.subresource == 'eviction'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} evicted {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'pod' }}"
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} started {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'pod' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} stopped {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'pod' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'pod' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-services
spec:
  resource:
    apiGroup: ""
    kind: Service
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} exposed {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'service' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'service' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : 'service' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-configmaps
spec:
  resource:
    apiGroup: ""
    kind: ConfigMap
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} added configuration {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed configuration {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed configuration {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-secrets
spec:
  resource:
    apiGroup: ""
    kind: Secret
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} added secret {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed secret {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed secret {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-namespaces
spec:
  resource:
    apiGroup: ""
    kind: Namespace
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created workspace {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed workspace {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated workspace {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-serviceaccounts
spec:
  resource:
    apiGroup: ""
    kind: ServiceAccount
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created identity {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed identity {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated identity {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-persistentvolumeclaims
spec:
  resource:
    apiGroup: ""
    kind: PersistentVolumeClaim
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} requested storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} released storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: core-persistentvolumes
spec:
  resource:
    apiGroup: ""
    kind: PersistentVolume
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} provisioned storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated storage {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
