# ActivityPolicies for rbac.authorization.k8s.io Kubernetes API group
# Resources: ClusterRole, ClusterRoleBinding, Role, RoleBinding

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-clusterroles
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created cluster role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed cluster role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated cluster role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified cluster role {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-clusterrolebindings
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} granted cluster permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} revoked cluster permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated cluster permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified cluster permissions {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-roles
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} created role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated role {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified role {{ link(audit.objectRef.name, audit.objectRef) }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-rolebindings
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: RoleBinding
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} granted permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} revoked permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} updated permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
    - match: "true"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} modified permissions {{ link(audit.objectRef.name, audit.objectRef) }}"
