# ActivityPolicies for rbac.authorization.k8s.io Kubernetes API group
# Resources: ClusterRole, ClusterRoleBinding, Role, RoleBinding
#
# These policies only generate activities for write operations (create, update, patch, delete).
# Read operations (get, list, watch) are excluded as they don't represent meaningful state changes.

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-clusterroles
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} defined cluster-wide permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed cluster-wide permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed cluster-wide permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-clusterrolebindings
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} granted cluster-wide access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} revoked cluster-wide access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed cluster-wide access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-roles
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} defined permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} removed permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed permissions {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"

---
apiVersion: activity.miloapis.com/v1alpha1
kind: ActivityPolicy
metadata:
  name: rbac-rolebindings
spec:
  resource:
    apiGroup: rbac.authorization.k8s.io
    kind: RoleBinding
  auditRules:
    - match: "audit.verb == 'create'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} granted access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb == 'delete'"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} revoked access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
    - match: "audit.verb in ['update', 'patch']"
      summary: "{{ actor.startsWith('system:') ? 'System' : link(actor, actorRef) }} changed access {{ has(audit.objectRef.name) ? link(audit.objectRef.name, audit.objectRef) : '' }}"
