// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisactivityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	versioned "go.miloapis.com/activity/pkg/client/clientset/versioned"
	internalinterfaces "go.miloapis.com/activity/pkg/client/informers/externalversions/internalinterfaces"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/listers/activity/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ActivityInformer provides access to a shared informer and lister for
// Activities.
type ActivityInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() activityv1alpha1.ActivityLister
}

type activityInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewActivityInformer constructs a new informer for Activity type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewActivityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredActivityInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredActivityInformer constructs a new informer for Activity type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredActivityInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().Activities(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().Activities(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().Activities(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().Activities(namespace).Watch(ctx, options)
			},
		}, client),
		&apisactivityv1alpha1.Activity{},
		resyncPeriod,
		indexers,
	)
}

func (f *activityInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredActivityInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *activityInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisactivityv1alpha1.Activity{}, f.defaultInformer)
}

func (f *activityInformer) Lister() activityv1alpha1.ActivityLister {
	return activityv1alpha1.NewActivityLister(f.Informer().GetIndexer())
}
