// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "go.miloapis.com/activity/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Activities returns a ActivityInformer.
	Activities() ActivityInformer
	// ActivityPolicies returns a ActivityPolicyInformer.
	ActivityPolicies() ActivityPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Activities returns a ActivityInformer.
func (v *version) Activities() ActivityInformer {
	return &activityInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ActivityPolicies returns a ActivityPolicyInformer.
func (v *version) ActivityPolicies() ActivityPolicyInformer {
	return &activityPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
