// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisactivityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	versioned "go.miloapis.com/activity/pkg/client/clientset/versioned"
	internalinterfaces "go.miloapis.com/activity/pkg/client/informers/externalversions/internalinterfaces"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/listers/activity/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ReindexJobInformer provides access to a shared informer and lister for
// ReindexJobs.
type ReindexJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() activityv1alpha1.ReindexJobLister
}

type reindexJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewReindexJobInformer constructs a new informer for ReindexJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReindexJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredReindexJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredReindexJobInformer constructs a new informer for ReindexJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredReindexJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().ReindexJobs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().ReindexJobs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().ReindexJobs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ActivityV1alpha1().ReindexJobs(namespace).Watch(ctx, options)
			},
		}, client),
		&apisactivityv1alpha1.ReindexJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *reindexJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredReindexJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *reindexJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisactivityv1alpha1.ReindexJob{}, f.defaultInformer)
}

func (f *reindexJobInformer) Lister() activityv1alpha1.ReindexJobLister {
	return activityv1alpha1.NewReindexJobLister(f.Informer().GetIndexer())
}
