// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// ActivityQueriesGetter has a method to return a ActivityQueryInterface.
// A group's client should implement this interface.
type ActivityQueriesGetter interface {
	ActivityQueries() ActivityQueryInterface
}

// ActivityQueryInterface has methods to work with ActivityQuery resources.
type ActivityQueryInterface interface {
	Create(ctx context.Context, activityQuery *activityv1alpha1.ActivityQuery, opts v1.CreateOptions) (*activityv1alpha1.ActivityQuery, error)
	ActivityQueryExpansion
}

// activityQueries implements ActivityQueryInterface
type activityQueries struct {
	*gentype.Client[*activityv1alpha1.ActivityQuery]
}

// newActivityQueries returns a ActivityQueries
func newActivityQueries(c *ActivityV1alpha1Client) *activityQueries {
	return &activityQueries{
		gentype.NewClient[*activityv1alpha1.ActivityQuery](
			"activityqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.ActivityQuery { return &activityv1alpha1.ActivityQuery{} },
		),
	}
}
