// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ActivitiesGetter has a method to return a ActivityInterface.
// A group's client should implement this interface.
type ActivitiesGetter interface {
	Activities(namespace string) ActivityInterface
}

// ActivityInterface has methods to work with Activity resources.
type ActivityInterface interface {
	Create(ctx context.Context, activity *activityv1alpha1.Activity, opts v1.CreateOptions) (*activityv1alpha1.Activity, error)
	Update(ctx context.Context, activity *activityv1alpha1.Activity, opts v1.UpdateOptions) (*activityv1alpha1.Activity, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*activityv1alpha1.Activity, error)
	List(ctx context.Context, opts v1.ListOptions) (*activityv1alpha1.ActivityList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *activityv1alpha1.Activity, err error)
	ActivityExpansion
}

// activities implements ActivityInterface
type activities struct {
	*gentype.ClientWithList[*activityv1alpha1.Activity, *activityv1alpha1.ActivityList]
}

// newActivities returns a Activities
func newActivities(c *ActivityV1alpha1Client, namespace string) *activities {
	return &activities{
		gentype.NewClientWithList[*activityv1alpha1.Activity, *activityv1alpha1.ActivityList](
			"activities",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *activityv1alpha1.Activity { return &activityv1alpha1.Activity{} },
			func() *activityv1alpha1.ActivityList { return &activityv1alpha1.ActivityList{} },
		),
	}
}
