// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// ActivityFacetQueriesGetter has a method to return a ActivityFacetQueryInterface.
// A group's client should implement this interface.
type ActivityFacetQueriesGetter interface {
	ActivityFacetQueries() ActivityFacetQueryInterface
}

// ActivityFacetQueryInterface has methods to work with ActivityFacetQuery resources.
type ActivityFacetQueryInterface interface {
	Create(ctx context.Context, activityFacetQuery *activityv1alpha1.ActivityFacetQuery, opts v1.CreateOptions) (*activityv1alpha1.ActivityFacetQuery, error)
	ActivityFacetQueryExpansion
}

// activityFacetQueries implements ActivityFacetQueryInterface
type activityFacetQueries struct {
	*gentype.Client[*activityv1alpha1.ActivityFacetQuery]
}

// newActivityFacetQueries returns a ActivityFacetQueries
func newActivityFacetQueries(c *ActivityV1alpha1Client) *activityFacetQueries {
	return &activityFacetQueries{
		gentype.NewClient[*activityv1alpha1.ActivityFacetQuery](
			"activityfacetqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.ActivityFacetQuery { return &activityv1alpha1.ActivityFacetQuery{} },
		),
	}
}
