// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ActivityPoliciesGetter has a method to return a ActivityPolicyInterface.
// A group's client should implement this interface.
type ActivityPoliciesGetter interface {
	ActivityPolicies() ActivityPolicyInterface
}

// ActivityPolicyInterface has methods to work with ActivityPolicy resources.
type ActivityPolicyInterface interface {
	Create(ctx context.Context, activityPolicy *activityv1alpha1.ActivityPolicy, opts v1.CreateOptions) (*activityv1alpha1.ActivityPolicy, error)
	Update(ctx context.Context, activityPolicy *activityv1alpha1.ActivityPolicy, opts v1.UpdateOptions) (*activityv1alpha1.ActivityPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, activityPolicy *activityv1alpha1.ActivityPolicy, opts v1.UpdateOptions) (*activityv1alpha1.ActivityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*activityv1alpha1.ActivityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*activityv1alpha1.ActivityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *activityv1alpha1.ActivityPolicy, err error)
	ActivityPolicyExpansion
}

// activityPolicies implements ActivityPolicyInterface
type activityPolicies struct {
	*gentype.ClientWithList[*activityv1alpha1.ActivityPolicy, *activityv1alpha1.ActivityPolicyList]
}

// newActivityPolicies returns a ActivityPolicies
func newActivityPolicies(c *ActivityV1alpha1Client) *activityPolicies {
	return &activityPolicies{
		gentype.NewClientWithList[*activityv1alpha1.ActivityPolicy, *activityv1alpha1.ActivityPolicyList](
			"activitypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.ActivityPolicy { return &activityv1alpha1.ActivityPolicy{} },
			func() *activityv1alpha1.ActivityPolicyList { return &activityv1alpha1.ActivityPolicyList{} },
		),
	}
}
