// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ActivityV1alpha1Interface interface {
	RESTClient() rest.Interface
	ActivityFacetQueriesGetter
	ActivityPoliciesGetter
	ActivityQueriesGetter
	AuditLogFacetsQueriesGetter
	AuditLogQueriesGetter
	PolicyPreviewsGetter
}

// ActivityV1alpha1Client is used to interact with features provided by the activity.miloapis.com group.
type ActivityV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ActivityV1alpha1Client) ActivityFacetQueries() ActivityFacetQueryInterface {
	return newActivityFacetQueries(c)
}

func (c *ActivityV1alpha1Client) ActivityPolicies() ActivityPolicyInterface {
	return newActivityPolicies(c)
}

func (c *ActivityV1alpha1Client) ActivityQueries() ActivityQueryInterface {
	return newActivityQueries(c)
}

func (c *ActivityV1alpha1Client) AuditLogFacetsQueries() AuditLogFacetsQueryInterface {
	return newAuditLogFacetsQueries(c)
}

func (c *ActivityV1alpha1Client) AuditLogQueries() AuditLogQueryInterface {
	return newAuditLogQueries(c)
}

func (c *ActivityV1alpha1Client) PolicyPreviews() PolicyPreviewInterface {
	return newPolicyPreviews(c)
}

// NewForConfig creates a new ActivityV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ActivityV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ActivityV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ActivityV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ActivityV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ActivityV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ActivityV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ActivityV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ActivityV1alpha1Client {
	return &ActivityV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := activityv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ActivityV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
