// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// AuditLogQueriesGetter has a method to return a AuditLogQueryInterface.
// A group's client should implement this interface.
type AuditLogQueriesGetter interface {
	AuditLogQueries() AuditLogQueryInterface
}

// AuditLogQueryInterface has methods to work with AuditLogQuery resources.
type AuditLogQueryInterface interface {
	Create(ctx context.Context, auditLogQuery *activityv1alpha1.AuditLogQuery, opts v1.CreateOptions) (*activityv1alpha1.AuditLogQuery, error)
	AuditLogQueryExpansion
}

// auditLogQueries implements AuditLogQueryInterface
type auditLogQueries struct {
	*gentype.Client[*activityv1alpha1.AuditLogQuery]
}

// newAuditLogQueries returns a AuditLogQueries
func newAuditLogQueries(c *ActivityV1alpha1Client) *auditLogQueries {
	return &auditLogQueries{
		gentype.NewClient[*activityv1alpha1.AuditLogQuery](
			"auditlogqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.AuditLogQuery { return &activityv1alpha1.AuditLogQuery{} },
		),
	}
}
