// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// AuditLogFacetsQueriesGetter has a method to return a AuditLogFacetsQueryInterface.
// A group's client should implement this interface.
type AuditLogFacetsQueriesGetter interface {
	AuditLogFacetsQueries() AuditLogFacetsQueryInterface
}

// AuditLogFacetsQueryInterface has methods to work with AuditLogFacetsQuery resources.
type AuditLogFacetsQueryInterface interface {
	Create(ctx context.Context, auditLogFacetsQuery *activityv1alpha1.AuditLogFacetsQuery, opts v1.CreateOptions) (*activityv1alpha1.AuditLogFacetsQuery, error)
	AuditLogFacetsQueryExpansion
}

// auditLogFacetsQueries implements AuditLogFacetsQueryInterface
type auditLogFacetsQueries struct {
	*gentype.Client[*activityv1alpha1.AuditLogFacetsQuery]
}

// newAuditLogFacetsQueries returns a AuditLogFacetsQueries
func newAuditLogFacetsQueries(c *ActivityV1alpha1Client) *auditLogFacetsQueries {
	return &auditLogFacetsQueries{
		gentype.NewClient[*activityv1alpha1.AuditLogFacetsQuery](
			"auditlogfacetsqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.AuditLogFacetsQuery { return &activityv1alpha1.AuditLogFacetsQuery{} },
		),
	}
}
