// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// EventFacetQueriesGetter has a method to return a EventFacetQueryInterface.
// A group's client should implement this interface.
type EventFacetQueriesGetter interface {
	EventFacetQueries() EventFacetQueryInterface
}

// EventFacetQueryInterface has methods to work with EventFacetQuery resources.
type EventFacetQueryInterface interface {
	Create(ctx context.Context, eventFacetQuery *activityv1alpha1.EventFacetQuery, opts v1.CreateOptions) (*activityv1alpha1.EventFacetQuery, error)
	EventFacetQueryExpansion
}

// eventFacetQueries implements EventFacetQueryInterface
type eventFacetQueries struct {
	*gentype.Client[*activityv1alpha1.EventFacetQuery]
}

// newEventFacetQueries returns a EventFacetQueries
func newEventFacetQueries(c *ActivityV1alpha1Client) *eventFacetQueries {
	return &eventFacetQueries{
		gentype.NewClient[*activityv1alpha1.EventFacetQuery](
			"eventfacetqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.EventFacetQuery { return &activityv1alpha1.EventFacetQuery{} },
		),
	}
}
