// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// EventQueriesGetter has a method to return a EventQueryInterface.
// A group's client should implement this interface.
type EventQueriesGetter interface {
	EventQueries() EventQueryInterface
}

// EventQueryInterface has methods to work with EventQuery resources.
type EventQueryInterface interface {
	Create(ctx context.Context, eventQuery *activityv1alpha1.EventQuery, opts v1.CreateOptions) (*activityv1alpha1.EventQuery, error)
	EventQueryExpansion
}

// eventQueries implements EventQueryInterface
type eventQueries struct {
	*gentype.Client[*activityv1alpha1.EventQuery]
}

// newEventQueries returns a EventQueries
func newEventQueries(c *ActivityV1alpha1Client) *eventQueries {
	return &eventQueries{
		gentype.NewClient[*activityv1alpha1.EventQuery](
			"eventqueries",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.EventQuery { return &activityv1alpha1.EventQuery{} },
		),
	}
}
