// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ActivityExpansion interface{}

type ActivityFacetQueryExpansion interface{}

type ActivityPolicyExpansion interface{}

type ActivityQueryExpansion interface{}

type AuditLogFacetsQueryExpansion interface{}

type AuditLogQueryExpansion interface{}

type EventFacetQueryExpansion interface{}

type EventQueryExpansion interface{}

type PolicyPreviewExpansion interface{}

type ReindexJobExpansion interface{}
