// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
)

// PolicyPreviewsGetter has a method to return a PolicyPreviewInterface.
// A group's client should implement this interface.
type PolicyPreviewsGetter interface {
	PolicyPreviews() PolicyPreviewInterface
}

// PolicyPreviewInterface has methods to work with PolicyPreview resources.
type PolicyPreviewInterface interface {
	Create(ctx context.Context, policyPreview *activityv1alpha1.PolicyPreview, opts v1.CreateOptions) (*activityv1alpha1.PolicyPreview, error)
	PolicyPreviewExpansion
}

// policyPreviews implements PolicyPreviewInterface
type policyPreviews struct {
	*gentype.Client[*activityv1alpha1.PolicyPreview]
}

// newPolicyPreviews returns a PolicyPreviews
func newPolicyPreviews(c *ActivityV1alpha1Client) *policyPreviews {
	return &policyPreviews{
		gentype.NewClient[*activityv1alpha1.PolicyPreview](
			"policypreviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *activityv1alpha1.PolicyPreview { return &activityv1alpha1.PolicyPreview{} },
		),
	}
}
