// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activityv1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	scheme "go.miloapis.com/activity/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReindexJobsGetter has a method to return a ReindexJobInterface.
// A group's client should implement this interface.
type ReindexJobsGetter interface {
	ReindexJobs(namespace string) ReindexJobInterface
}

// ReindexJobInterface has methods to work with ReindexJob resources.
type ReindexJobInterface interface {
	Create(ctx context.Context, reindexJob *activityv1alpha1.ReindexJob, opts v1.CreateOptions) (*activityv1alpha1.ReindexJob, error)
	Update(ctx context.Context, reindexJob *activityv1alpha1.ReindexJob, opts v1.UpdateOptions) (*activityv1alpha1.ReindexJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, reindexJob *activityv1alpha1.ReindexJob, opts v1.UpdateOptions) (*activityv1alpha1.ReindexJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*activityv1alpha1.ReindexJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*activityv1alpha1.ReindexJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *activityv1alpha1.ReindexJob, err error)
	ReindexJobExpansion
}

// reindexJobs implements ReindexJobInterface
type reindexJobs struct {
	*gentype.ClientWithList[*activityv1alpha1.ReindexJob, *activityv1alpha1.ReindexJobList]
}

// newReindexJobs returns a ReindexJobs
func newReindexJobs(c *ActivityV1alpha1Client, namespace string) *reindexJobs {
	return &reindexJobs{
		gentype.NewClientWithList[*activityv1alpha1.ReindexJob, *activityv1alpha1.ReindexJobList](
			"reindexjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *activityv1alpha1.ReindexJob { return &activityv1alpha1.ReindexJob{} },
			func() *activityv1alpha1.ReindexJobList { return &activityv1alpha1.ReindexJobList{} },
		),
	}
}
