name: Publish UI to NPM

on:
  push:

jobs:
  publish:
    uses: datum-cloud/actions/.github/workflows/publish-npm-package.yaml@v1.10.0
    with:
      package-name: "@datum-cloud/activity-ui"
      package-path: ui
    secrets: inherit
