name: Publish UI to NPM

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    uses: datum-cloud/actions/.github/workflows/publish-npm-package.yaml@v1.12.1
    with:
      package-name: "@datum-cloud/activity-ui"
      package-path: ui
      release-mode: ${{ github.event_name == 'release' && 'release' || 'dev' }}
    secrets: inherit
