// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEventFacetQueries implements EventFacetQueryInterface
type fakeEventFacetQueries struct {
	*gentype.FakeClient[*v1alpha1.EventFacetQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeEventFacetQueries(fake *FakeActivityV1alpha1) activityv1alpha1.EventFacetQueryInterface {
	return &fakeEventFacetQueries{
		gentype.NewFakeClient[*v1alpha1.EventFacetQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("eventfacetqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("EventFacetQuery"),
			func() *v1alpha1.EventFacetQuery { return &v1alpha1.EventFacetQuery{} },
		),
		fake,
	}
}
