// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActivityQueries implements ActivityQueryInterface
type fakeActivityQueries struct {
	*gentype.FakeClient[*v1alpha1.ActivityQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeActivityQueries(fake *FakeActivityV1alpha1) activityv1alpha1.ActivityQueryInterface {
	return &fakeActivityQueries{
		gentype.NewFakeClient[*v1alpha1.ActivityQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("activityqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("ActivityQuery"),
			func() *v1alpha1.ActivityQuery { return &v1alpha1.ActivityQuery{} },
		),
		fake,
	}
}
