// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePolicyPreviews implements PolicyPreviewInterface
type fakePolicyPreviews struct {
	*gentype.FakeClient[*v1alpha1.PolicyPreview]
	Fake *FakeActivityV1alpha1
}

func newFakePolicyPreviews(fake *FakeActivityV1alpha1) activityv1alpha1.PolicyPreviewInterface {
	return &fakePolicyPreviews{
		gentype.NewFakeClient[*v1alpha1.PolicyPreview](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("policypreviews"),
			v1alpha1.SchemeGroupVersion.WithKind("PolicyPreview"),
			func() *v1alpha1.PolicyPreview { return &v1alpha1.PolicyPreview{} },
		),
		fake,
	}
}
