// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEventQueries implements EventQueryInterface
type fakeEventQueries struct {
	*gentype.FakeClient[*v1alpha1.EventQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeEventQueries(fake *FakeActivityV1alpha1) activityv1alpha1.EventQueryInterface {
	return &fakeEventQueries{
		gentype.NewFakeClient[*v1alpha1.EventQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("eventqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("EventQuery"),
			func() *v1alpha1.EventQuery { return &v1alpha1.EventQuery{} },
		),
		fake,
	}
}
