// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActivities implements ActivityInterface
type fakeActivities struct {
	*gentype.FakeClientWithList[*v1alpha1.Activity, *v1alpha1.ActivityList]
	Fake *FakeActivityV1alpha1
}

func newFakeActivities(fake *FakeActivityV1alpha1, namespace string) activityv1alpha1.ActivityInterface {
	return &fakeActivities{
		gentype.NewFakeClientWithList[*v1alpha1.Activity, *v1alpha1.ActivityList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("activities"),
			v1alpha1.SchemeGroupVersion.WithKind("Activity"),
			func() *v1alpha1.Activity { return &v1alpha1.Activity{} },
			func() *v1alpha1.ActivityList { return &v1alpha1.ActivityList{} },
			func(dst, src *v1alpha1.ActivityList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ActivityList) []*v1alpha1.Activity { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ActivityList, items []*v1alpha1.Activity) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
