// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActivityPolicies implements ActivityPolicyInterface
type fakeActivityPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.ActivityPolicy, *v1alpha1.ActivityPolicyList]
	Fake *FakeActivityV1alpha1
}

func newFakeActivityPolicies(fake *FakeActivityV1alpha1) activityv1alpha1.ActivityPolicyInterface {
	return &fakeActivityPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.ActivityPolicy, *v1alpha1.ActivityPolicyList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("activitypolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("ActivityPolicy"),
			func() *v1alpha1.ActivityPolicy { return &v1alpha1.ActivityPolicy{} },
			func() *v1alpha1.ActivityPolicyList { return &v1alpha1.ActivityPolicyList{} },
			func(dst, src *v1alpha1.ActivityPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ActivityPolicyList) []*v1alpha1.ActivityPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ActivityPolicyList, items []*v1alpha1.ActivityPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
