// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeReindexJobs implements ReindexJobInterface
type fakeReindexJobs struct {
	*gentype.FakeClientWithList[*v1alpha1.ReindexJob, *v1alpha1.ReindexJobList]
	Fake *FakeActivityV1alpha1
}

func newFakeReindexJobs(fake *FakeActivityV1alpha1, namespace string) activityv1alpha1.ReindexJobInterface {
	return &fakeReindexJobs{
		gentype.NewFakeClientWithList[*v1alpha1.ReindexJob, *v1alpha1.ReindexJobList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("reindexjobs"),
			v1alpha1.SchemeGroupVersion.WithKind("ReindexJob"),
			func() *v1alpha1.ReindexJob { return &v1alpha1.ReindexJob{} },
			func() *v1alpha1.ReindexJobList { return &v1alpha1.ReindexJobList{} },
			func(dst, src *v1alpha1.ReindexJobList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ReindexJobList) []*v1alpha1.ReindexJob { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ReindexJobList, items []*v1alpha1.ReindexJob) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
