// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeActivityV1alpha1 struct {
	*testing.Fake
}

func (c *FakeActivityV1alpha1) Activities(namespace string) v1alpha1.ActivityInterface {
	return newFakeActivities(c, namespace)
}

func (c *FakeActivityV1alpha1) ActivityFacetQueries() v1alpha1.ActivityFacetQueryInterface {
	return newFakeActivityFacetQueries(c)
}

func (c *FakeActivityV1alpha1) ActivityPolicies() v1alpha1.ActivityPolicyInterface {
	return newFakeActivityPolicies(c)
}

func (c *FakeActivityV1alpha1) ActivityQueries() v1alpha1.ActivityQueryInterface {
	return newFakeActivityQueries(c)
}

func (c *FakeActivityV1alpha1) AuditLogFacetsQueries() v1alpha1.AuditLogFacetsQueryInterface {
	return newFakeAuditLogFacetsQueries(c)
}

func (c *FakeActivityV1alpha1) AuditLogQueries() v1alpha1.AuditLogQueryInterface {
	return newFakeAuditLogQueries(c)
}

func (c *FakeActivityV1alpha1) EventFacetQueries() v1alpha1.EventFacetQueryInterface {
	return newFakeEventFacetQueries(c)
}

func (c *FakeActivityV1alpha1) EventQueries() v1alpha1.EventQueryInterface {
	return newFakeEventQueries(c)
}

func (c *FakeActivityV1alpha1) PolicyPreviews() v1alpha1.PolicyPreviewInterface {
	return newFakePolicyPreviews(c)
}

func (c *FakeActivityV1alpha1) ReindexJobs(namespace string) v1alpha1.ReindexJobInterface {
	return newFakeReindexJobs(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeActivityV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
