// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeActivityV1alpha1 struct {
	*testing.Fake
}

func (c *FakeActivityV1alpha1) AuditLogQueries() v1alpha1.AuditLogQueryInterface {
	return newFakeAuditLogQueries(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeActivityV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
