// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuditLogQueries implements AuditLogQueryInterface
type fakeAuditLogQueries struct {
	*gentype.FakeClient[*v1alpha1.AuditLogQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeAuditLogQueries(fake *FakeActivityV1alpha1) activityv1alpha1.AuditLogQueryInterface {
	return &fakeAuditLogQueries{
		gentype.NewFakeClient[*v1alpha1.AuditLogQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("auditlogqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("AuditLogQuery"),
			func() *v1alpha1.AuditLogQuery { return &v1alpha1.AuditLogQuery{} },
		),
		fake,
	}
}
