// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuditLogFacetsQueries implements AuditLogFacetsQueryInterface
type fakeAuditLogFacetsQueries struct {
	*gentype.FakeClient[*v1alpha1.AuditLogFacetsQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeAuditLogFacetsQueries(fake *FakeActivityV1alpha1) activityv1alpha1.AuditLogFacetsQueryInterface {
	return &fakeAuditLogFacetsQueries{
		gentype.NewFakeClient[*v1alpha1.AuditLogFacetsQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("auditlogfacetsqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("AuditLogFacetsQuery"),
			func() *v1alpha1.AuditLogFacetsQuery { return &v1alpha1.AuditLogFacetsQuery{} },
		),
		fake,
	}
}
