// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/activity/pkg/apis/activity/v1alpha1"
	activityv1alpha1 "go.miloapis.com/activity/pkg/client/clientset/versioned/typed/activity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActivityFacetQueries implements ActivityFacetQueryInterface
type fakeActivityFacetQueries struct {
	*gentype.FakeClient[*v1alpha1.ActivityFacetQuery]
	Fake *FakeActivityV1alpha1
}

func newFakeActivityFacetQueries(fake *FakeActivityV1alpha1) activityv1alpha1.ActivityFacetQueryInterface {
	return &fakeActivityFacetQueries{
		gentype.NewFakeClient[*v1alpha1.ActivityFacetQuery](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("activityfacetqueries"),
			v1alpha1.SchemeGroupVersion.WithKind("ActivityFacetQuery"),
			func() *v1alpha1.ActivityFacetQuery { return &v1alpha1.ActivityFacetQuery{} },
		),
		fake,
	}
}
